SHMEM/Stencil/stencil.c

pSync and pWrk arrays were not sized correctly, leading to memory
corruption.  pSync arrays also do not need to be re-initialized after
they are used.
Signed-off-by: James Dinan <james.dinan@intel.com>

Fix errors in collecive calls

---

.travis.yml
travis/build-run-prk.sh
travis/install-grappa.sh

I made some progress on Grappa but it still does not work.  Give up and disable Grappa for now.

Travis CI Grappa - round 2

---

.travis.yml
OPENMP/Reduce/reduce.c
travis/install-clang.sh
travis/install-deps.sh

- Enable Clang OpenMP via Homebrew on Mac.
- Fix OpenMP syntax error (false positive?).

Travis CI Clang OpenMP

---

.travis.yml
travis/build-run-prk.sh
travis/install-chapel.sh
travis/install-charm++.sh
travis/install-deps.sh

Chapel builds are working in Travis.  We do not have PRKs to test yet, so they are disabled for now.

Travis CI Chapel

---

travis/install-grappa.sh
travis/install-oshmpi.sh

this is a trivial modification to existing travis stuff

use git clone depth to speed up dep checkouts

---

SERIAL/Transpose/transpose.f90

no build system support yet...

serial Fortran transpose

---

.travis.yml
travis/build-run-prk.sh
travis/install-autotools.sh
travis/install-deps.sh
travis/install-hpx5.sh

This is just a download-and-build test.

Travis CI HPX-5

---

.travis.yml
travis/build-run-prk.sh
travis/install-deps.sh
travis/install-hpx3.sh
travis/install-hpx5.sh

HPX-3 and HPX-5 fixes.  Build from Git.

Travis CI HPX-3

---

FORTRAN/Stencil/stencil.f90
FORTRAN/Transpose/transpose.f90

This includes (1) comment cleanup (2) bug workaround for Intel 16

Fortran OpenMP

---

FORTRAN/Stencil/stencil.f90
FORTRAN/Synch_p2p/p2p.f90
FORTRAN/Transpose/transpose.f90

the latter returns aggregate time, which is not what we want

use omp_get_wtime instead of cpu_time with threads

---

UPC/README.md

We should add `$model/README.md` whenever there are important things to remember.

add a UPC readme for keeping track of useful stuff [ci skip]

---

CAF/Synch_p2p/Makefile
CAF/Synch_p2p/p2p-coarray.f90
CAF/Synch_p2p/p2p.f90
common/make.defs.in

Dear all,
this pull request adds a CAF-based Sync_p2p kernel.
Please consider only the source code if the Makefile and directory organization is not compliant with your plans.
Regards,
Alessandro

Synch_p2p CAF

---

.travis.yml
FORTRAN/Transpose/Makefile
FORTRAN/Transpose/transpose-pretty.f90
PYTHON/p2p.py
PYTHON/stencil-numpy.py
PYTHON/stencil.py
PYTHON/transpose-numpy.py
PYTHON/transpose.py
travis/build-run-prk.sh

I wrote Numpy Transpose and then the modern Fortran idiom to match it.

Python numpy

---

FORTRAN/Stencil/stencil-coarray.f90
FORTRAN/Stencil/stencil.f90
FORTRAN/Synch_p2p/p2p-coarray.f90

Dear all,
this pull request adds the coarray Fortran stencil kernel.
It currently works only with STAR stencil without tiling.
Cheers,
Alessandro

Coarray Fortran Stencil

---

.travis.yml
AMPI/DGEMM/Makefile
AMPI/Stencil/Makefile
CHARM++/Stencil/Makefile
FG_MPI/DGEMM/Makefile
FG_MPI/Stencil/Makefile
FORTRAN/Stencil/stencil-coarray.f90
MPI1/DGEMM/Makefile
MPI1/Stencil/Makefile
MPIOPENMP/Stencil/Makefile
MPIOPENMP/Transpose/Makefile
MPIRMA/Stencil/Makefile
MPISHM/Stencil/Makefile
travis/build-run-prk.sh
travis/install-chapel.sh
travis/install-clang.sh
travis/install-deps.sh
travis/install-gasnet.sh
travis/install-grappa.sh
travis/install-hpx3.sh
travis/install-hpx5.sh
travis/install-mpi.sh
travis/install-opencoarrays.sh

This patch fixes #97 and #98. Note that this code works only for STAR stencil without tiling.

Fix bug due to unevenly divisible size

---

.travis.yml
travis/build-run-prk.sh
travis/install-deps.sh
travis/install-mpi.sh
travis/install-opencoarrays.sh

At long last, the Linux OpenCoarrays Travis scripting works.

Travis OpenCoarrays 2

---

GRAPPA/Nstream/Makefile
GRAPPA/Nstream/nstream.cpp
GRAPPA/Random/Makefile
GRAPPA/Random/random.cpp
GRAPPA/Stencil/Makefile
GRAPPA/Stencil/stencil.cpp
GRAPPA/Synch_global/Makefile
GRAPPA/Synch_global/global.cpp
GRAPPA/Synch_p2p/p2p.cpp
GRAPPA/Transpose/Makefile
GRAPPA/Transpose/transpose.cpp
Makefile
travis/build-run-prk.sh

I have no idea what I did wrong with Git to make the recent Grappa contributions disappear.  My only guess is `git merge -s ours master` on the `intel-compilers-merge branch.

somehow the Grappa stuff was lost

---

AMPI/Sparse/sparse.c
AMPI/Stencil/stencil.c
FG_MPI/PIC-static/pic.c
FG_MPI/Sparse/sparse.c
FG_MPI/Stencil/stencil.c
MPI1/PIC-static/pic.c
MPI1/Sparse/sparse.c
MPI1/Stencil/stencil.c
MPIOPENMP/Stencil/stencil.c
MPIRMA/Stencil/stencil.c
MPISHM/Stencil/stencil.c
OPENMP/PIC/pic.c
OPENMP/Sparse/sparse.c
OPENMP/Stencil/stencil.c
SERIAL/PIC/pic.c
SERIAL/Sparse/sparse.c
SERIAL/Stencil/stencil.c
SHMEM/Stencil/stencil.c

...from all C-based implementations of Stenill, PIC, and Sparse.
Yeah, nothing interesting yet. I'm just getting started. :-)

remove trailing whitespace

---

PYTHON/p2p-numpy.py
PYTHON/p2p.py
PYTHON/stencil-numpy.py
PYTHON/stencil.py
PYTHON/transpose-numpy.py
PYTHON/transpose.py

wait for Travis CI before merging

convert to python3 with 2to3 -w

---

FORTRAN/Stencil/stencil-pretty.f90
FORTRAN/Stencil/stencil.f90
FORTRAN/Synch_p2p/p2p-coarray.f90
FORTRAN/Synch_p2p/p2p.f90

@zbeekman This addresses the issues I reported...

remove unnecessary stop statements at the end of programs

---

FORTRAN/Stencil/stencil-pretty.f90
FORTRAN/Transpose/transpose-pretty.f90
FORTRAN/Transpose/transpose.f90
common/make.defs.pgi

I've been kicking the tires on https://github.com/flang-compiler/flang...

PGI Flang workarounds

---

common/make.defs.cray

fix C++11 flag; add ACC flag [ci skip]

Cray make.defs update

---

Cxx11/add.cl
Cxx11/generate-opencl-stencil.py
Cxx11/prk_opencl.h
Cxx11/stencil-opencl.cc
Cxx11/transpose-opencl.cc
Cxx11/transpose.cl

Look for and test multiple devices using the highest precision they support (32 or 64).

OpenCL precision, multiple devices

---

Cxx11/Makefile
Cxx11/prk_cuda.h
Cxx11/prk_opencl.h
Cxx11/transpose-cuda.cu
common/make.defs.cuda

This is a crappy implementation of transpose.  Mostly adding now to get the build infrastructure in.  Will implement stencil and improve transpose some day.
The biggest takeaway from this port is that OpenCL is just as easy, if not easier to write, and performs similarly on NVIDIA GPUs.

CUDA transpose

---

Cxx11/Makefile
Cxx11/stencil-vector-pstl.cc

Works with Intel 18.  Skipping Travis.

add PSTL stencil

---

Cxx11/Makefile
Cxx11/stencil-vector-rangefor.cc
Cxx11/transpose-vector-rangefor.cc

Requires Boost irange.
No Travis testing yet.

C++11 range-based for implementation

---

Cxx11/transpose-valarray.cc
Cxx11/transpose-vector-cilk.cc
Cxx11/transpose-vector-pstl.cc
Cxx11/transpose-vector-rangefor.cc
Cxx11/transpose-vector.cc

This needs to be repeated for Fortran and possibly Python.

C++11 kernel fusion

---

travis/install-mpi.sh

see https://lists.mpich.org/pipermail/discuss/2016-May/004764.html
for details.

MPICH 3.2 built with Clang on Linux has a bug

---

.gitignore
C1z/Makefile
C1z/prk_util.h
C1z/transpose-thread.c
travis/build-run-prk.sh
travis/install-deps.sh
travis/install-musl.sh

C11 threads not tested because not supported on Mac.

add C11 thread (Pthread) transpose

---

Cxx11/Makefile
Cxx11/prk_util.h

preprocessor can't handle strings it seems (or i am stupid)

fix issues with TBB_PARTITIONER control

---

Cxx11/prk_util.h

...and don't blame ICC for GCC's shortcomings.

detect ancient stdlib

---

FORTRAN/Makefile

Better detection of what features different compilers support.

Fortran makefile smarts

---

Cxx11/Makefile
Cxx11/prk_util.h
Cxx11/stencil-vector-pstl.cc
Cxx11/transpose-vector-pstl.cc
common/make.defs.gcc
common/make.defs.intel
common/make.defs.llvm
travis/build-run-prk.sh
travis/install-deps.sh
travis/install-pstl.sh
travis/install-tbb.sh

Intel Parallel STL is OSS so we can use with GCC and Clang.
https://github.com/intel/parallelstl

support Intel PSTL for Clang and GCC

---

PYTHON/nstream-numpy.py
PYTHON/nstream.py
PYTHON/transpose-numpy.py
PYTHON/transpose.py

@rfvander Here is something for you to review 😄

Python nstream

---

travis/build-run-prk.sh
travis/install-raja.sh

https://github.com/sourceryinstitute/OpenCoarrays/issues/460#issuecomment-342206845

use oversubscribe with cafrun 

---

travis/install-kokkos.sh

see https://github.com/kokkos/kokkos/pull/1244

try kokkos develop branch

---

.travis.yml
PYTHON/dgemm-numpy.py
PYTHON/dgemm.py
PYTHON/nstream-numpy.py
PYTHON/nstream.py
PYTHON/p2p-numpy.py
PYTHON/p2p.py
PYTHON/sparse-numpy.py
PYTHON/sparse-scipy.py
PYTHON/sparse.py
PYTHON/stencil-numba.py
PYTHON/stencil-numpy.py
PYTHON/stencil.py
PYTHON/transpose-numpy.py
PYTHON/transpose.py
common/make.defs.intel
travis/build-run-prk.sh
travis/install-raja.sh

@rfvander
- How important is the column index sorting?
- Do I need to support the `REVERSE` stuff or was that just for debugging?
In any case, please don't merge yet because this depends on https://github.com/ParRes/Kernels/pull/283, which isn't ready yet.

Python sparse

---

Cxx11/Makefile
Cxx11/nstream-kokkos.cc
Cxx11/nstream-opencl.cc
Cxx11/nstream-openmp-target.cc
Cxx11/nstream-valarray.cc
Cxx11/nstream-vector-openmp.cc
Cxx11/nstream-vector-pstl.cc
Cxx11/nstream-vector-raja.cc
Cxx11/nstream-vector-rangefor.cc
Cxx11/nstream-vector-taskloop.cc
Cxx11/nstream-vector-tbb.cc
Cxx11/nstream-vector.cc
Cxx11/nstream.cl
Cxx11/transpose-kokkos.cc
Cxx11/transpose-vector-taskloop.cc
FORTRAN/Makefile
FORTRAN/nstream-openmp-target.f90
FORTRAN/nstream-ornlacc.f90
FORTRAN/nstream-pretty.f90
FORTRAN/nstream-taskloop-openmp.f90
FORTRAN/nstream.f90
FORTRAN/p2p-ornlacc.f90
FORTRAN/stencil-ornlacc.f90
FORTRAN/transpose-ornlacc.f90
PYTHON/nstream-numpy.py
PYTHON/nstream.py
common/make.defs.intel
travis/build-run-prk.sh

@rfvander Please do not merge.  I want Travis CI to validate everything first.
This is only C++ at the moment, but Fortran will be added soon.
I did not implement the `offset` thing because it was lost when I converted to Python.  Is it really necessary?  I wrote these implementations using separate buffers for each vector, so I'm not sure how much sense offset makes, unless it is padding on the front of a vector.

Nstream ports

---

PYTHON/p2p-numba.py

thanks to Todd Anderson of PCL for suggesting this.

add p2p with Numba

---

Cxx11/Makefile
Cxx11/nstream-cublas.cu
Cxx11/nstream-cuda.cu
Cxx11/nstream-kokkos.cc
Cxx11/nstream-opencl.cc
Cxx11/nstream-openmp-target.cc
Cxx11/nstream-valarray.cc
Cxx11/nstream-vector-openmp.cc
Cxx11/nstream-vector-pstl.cc
Cxx11/nstream-vector-raja.cc
Cxx11/nstream-vector-rangefor.cc
Cxx11/nstream-vector-taskloop.cc
Cxx11/nstream-vector-tbb.cc
Cxx11/nstream-vector.cc
Cxx11/prk_cuda.h
Cxx11/prk_util.h
Cxx11/transpose-cublas.cu
Cxx11/transpose-cuda.cu
Cxx11/transpose-vector-taskloop.cc
common/make.defs.cuda
common/make.defs.gcc

~Still need to test this with an actual CUDA implementation, not just Coriander.~
Only nstream.  No dgemm yet.  The title is correct.  The branch name is not.

CUDA nstream

---

Cxx11/Makefile
Cxx11/generate-sycl-stencil.py
Cxx11/nstream-sycl.cc
Cxx11/nstream-vector-pstl.cc
Cxx11/prk_util.h
Cxx11/stencil-sycl.cc
Cxx11/stencil_sycl.hpp
Cxx11/transpose-kokkos.cc
Cxx11/transpose-sycl.cc
README.md
common/make.defs.gcc
common/make.defs.intel
common/make.defs.llvm

Travis CI support will be added in a subsequent commit.
Most common `make.defs.${toolchain}` were modified appropriately.

new implementation: SYCL

---

Cxx11/generate-sycl-stencil.py
Cxx11/stencil-sycl.cc
common/make.defs.gcc
common/make.defs.intel
common/make.defs.llvm
travis/build-run-prk.sh
travis/install-deps.sh
travis/install-pstl.sh
travis/install-sycl.sh

SYCL with Travis support

---

.gitignore
Cxx11/Makefile
Cxx11/nstream-valarray-boost-compute.cc
Cxx11/nstream-vector-boost-compute.cc
Cxx11/prk_util.h
common/make.defs.cray
common/make.defs.gcc
common/make.defs.intel
common/make.defs.llvm
travis/build-run-prk.sh
travis/install-boost.sh
travis/install-pstl.sh

If no, why not?
Jeff is lazy.
Sort of.  Boost is supported already.  Compute comes with that.

Boost compute

---

.gitignore
Cxx11/Makefile
Cxx11/p2p-hyperplane-vector-ornlacc.cc
FORTRAN/Makefile
FORTRAN/nstream.f90
FORTRAN/p2p-async-ornlacc.f90
FORTRAN/p2p-innerloop-ornlacc.f90
travis/build-run-prk.sh

ORNL-ACC wavefront (C++ and Fortran)

---

.gitignore
Cxx11/Makefile
Cxx11/dgemm-cublas.cu
Cxx11/transpose-cublas.cu

- add a bunch of overdue ignoring
- twiddle transpose-cublas output

add CUBLAS DGEMM

---

Cxx11/dgemm-cblas.cc
Cxx11/dgemm-cublas.cu
common/make.defs.llvm

This adds testing of batched DGEMM in MKL CBLAS and CUBLAS.  It is not finished but I want to track it here in case others have comments.

DGEMM batched

---

Cxx11/Makefile
Cxx11/p2p-tasks-tbb.cc
common/make.defs.intel

add it later
Adding Threading Building Blocks (TBB) Flow Graph version of task based synch_p2p kernel. Pattern similar to improved OpenMP task version. Graph is created once, implementation is a token based approach (continue_msg) with back loop for the grid. 
Requires at least TBB 4.0 (2011).

TBB Flow Graph version of p2p

---

Cxx11/Makefile
Cxx11/p2p-tasks-tbb.cc
common/make.defs.intel
travis/build-run-prk.sh

TBB flowgraph

---

CODEOWNERS
Cxx11/Makefile
Cxx11/dgemm-cblas.cc
Cxx11/transpose-cblas.cc
README.md
travis/build-run-prk.sh
travis/install-mpi.sh

- MKL and Accelerate are supported via extensions
- add Travis support
- add 'cblas' target to Makefile

add CBLAS transpose

---

Cxx11/generate-sycl-stencil.py
Cxx11/nstream-sycl.cc
Cxx11/stencil-sycl.cc
Cxx11/stencil_sycl.hpp
Cxx11/transpose-sycl.cc

working on transpose and stencil

SYCL multi device and exceptions

---

Cxx11/nstream-opencl.cc
Cxx11/p2p-innerloop-opencl.cc
Cxx11/stencil-opencl.cc
Cxx11/transpose-opencl.cc

I have no idea how this was never a problem before...

do not incorrectly declare non-read-only buffers as read-only

---

Makefile

resolves https://github.com/ParRes/Kernels/issues/361

remove Rust from parent makefile to unbreak case when cargo missing

---

AMPI/Stencil/stencil.c
CHARM++/Stencil/stencil.C
FG_MPI/Stencil/stencil.c
MPI1/Stencil/stencil.c
MPIOPENMP/Stencil/stencil.c
MPIRMA/Stencil/stencil.c
MPISHM/Stencil/stencil.c
SHMEM/Stencil/stencil.c

fixes https://github.com/ParRes/Kernels/issues/278

avoid overflow

---

Cxx11/nstream-kokkos.cc
Cxx11/stencil-kokkos.cc
Cxx11/transpose-kokkos.cc

Fixes https://github.com/ParRes/Kernels/issues/377

add kokkos::fence where appropriate

---

.gitignore
FORTRAN/Makefile
FORTRAN/dgemm-openmp-target.f90
FORTRAN/dgemm-pretty.f90
FORTRAN/dgemm-taskloop-openmp.f90
FORTRAN/dgemm.f90
FORTRAN/nstream.f90
FORTRAN/stencil-pretty.f90
FORTRAN/transpose-pretty.f90
FORTRAN/transpose.f90

https://github.com/flang-compiler/flang/issues/298 is the one remaining blocking issue for the PRKs to use Flang as if it is a real Fortran 2008 compiler.

Flang is mostly Fortran 2008 complete now

---

C1z/Makefile
C1z/p2p-hyperplane-openmp.c
Cxx11/Makefile
Cxx11/prk_util.h
Cxx11/stencil-openmp-target.cc
travis/build-run-prk.sh

add hyperplane OpenMP to C1z

---

common/make.defs.llvm

Add https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md

add Intel SYCL toolchain to LLVM example

---

Cxx11/nstream-openmp-target.cc
Cxx11/transpose-openmp-target.cc
FORTRAN/dgemm-openmp-target.f90
FORTRAN/nstream-openmp-target.f90
FORTRAN/stencil-openmp-target.f90
FORTRAN/transpose-openmp-target.f90

should fix https://github.com/ParRes/Kernels/issues/410

do not map timers

---

common/make.defs.boost

https://github.com/boostorg/boost makes it a unique pain to include headers.
```sh
BOOSTFLAG=
BOOSTFLAG+=-I${BOOSTROOT}/circular_buffer/include
BOOSTFLAG+=-I${BOOSTROOT}/compute/include
BOOSTFLAG+=-I${BOOSTROOT}/algorithm/include
BOOSTFLAG+=-I${BOOSTROOT}/config/include
BOOSTFLAG+=-I${BOOSTROOT}/core/include
BOOSTFLAG+=-I${BOOSTROOT}/log/include
BOOSTFLAG+=-I${BOOSTROOT}/array/include
BOOSTFLAG+=-I${BOOSTROOT}/multi_array/include
BOOSTFLAG+=-I${BOOSTROOT}/optional/include
BOOSTFLAG+=-I${BOOSTROOT}/preprocessor/include
BOOSTFLAG+=-I${BOOSTROOT}/type_index/include
BOOSTFLAG+=-I${BOOSTROOT}/utility/include
BOOSTFLAG+=-I${BOOSTROOT}/assert/include
BOOSTFLAG+=-I${BOOSTROOT}/static_assert/include
BOOSTFLAG+=-I${BOOSTROOT}/exception/include
BOOSTFLAG+=-I${BOOSTROOT}/throw_exception/include …
```

add example of all the crap required when using boost github

---

Cxx11/nstream-cublas.cu
Cxx11/nstream-cuda.cu
Cxx11/nstream-device-thrust.cu
Cxx11/nstream-host-thrust.cc
Cxx11/nstream-kokkos.cc
Cxx11/nstream-occa.cc
Cxx11/nstream-opencl.cc
Cxx11/nstream-openmp-target.cc
Cxx11/nstream-openmp.cc
Cxx11/nstream-raja.cc
Cxx11/nstream-sycl-explicit.cc
Cxx11/nstream-sycl-usm.cc
Cxx11/nstream-sycl.cc
Cxx11/nstream.cc

fixes https://github.com/ParRes/Kernels/issues/407

C++ nstream error check precision fix

---

common/make.defs.ibmp9nv

more IBM fixes, Boost stuff

---

common/make.defs.oneapi

oneAPI make.defs

---

C1z/transpose-ispc.c
C1z/transpose.ispc

@jeffamstutz We did this in 5 minutes together at SC19 but I want to verify that I correctly implemented your suggestions to improve the use of ISPC in the PRK.

improve ISPC w/ help from Jeff Amstutz

---

travis/build-run-prk.sh
travis/install-deps.sh
travis/install-julia.sh
travis/install-kokkos.sh
travis/install-pstl.sh
travis/install-python.sh

This fixes issues with legacy C/OpenMP, Python, and Julia, at least.

fix Travis (Feb. 2020)

---

C1z/Makefile
C1z/transpose-ispc.c
C1z/transpose.ispc

I used ISPC's tasking syntax to thread `transpose-ispc` using OpenMP as the tasking system...got nice results.

add threaded versions of transpose-ispc via OpenMP

---

C1z/p2p-hyperplane-openmp.c

simplify arithmetic in p2p indexing

---

Cxx11/nstream-sycl-usm.cc
Cxx11/prk_sycl.h
Cxx11/stencil-sycl-usm.cc
Cxx11/transpose-sycl-usm.cc

add syclx:: for CodePlay USM

---

C1z/p2p-tasks-openmp.c
Cxx11/p2p-tasks-openmp.cc

workaround bug in ICC NextGen

---

.gitignore
FORTRAN/Makefile
FORTRAN/nstream-ga.F90
FORTRAN/transpose-ga.F90
travis/install-armci-mpi.sh
travis/install-ga.sh

`./travis/install-ga.sh` is present but GA is not tested by Travis CI.
https://hpc.pnnl.gov/globalarrays/api/fapi.shtml
`make.defs.*` will be present when this is done.

Global Arrays

---

.gitignore
C1z/Makefile
C1z/nstream-memkind.c
C1z/nstream-mmap.c
C1z/nstream-mpi.c
C1z/nstream-openmp.c
C1z/nstream-petsc.c
C1z/nstream-target.c
C1z/nstream-taskloop.c
C1z/p2p-hyperplane-openmp.c
C1z/p2p-simd-openmp.c
C1z/p2p-tasks-openmp.c
C1z/prk_openmp.h
C1z/prk_petsc.h
C1z/prk_util.h
C1z/stencil-openmp.c
C1z/stencil-target.c
C1z/stencil-taskloop.c
C1z/transpose-openmp.c
C1z/transpose-target.c
C1z/transpose-taskloop.c
travis/install-petsc.sh

`install-petsc.sh` is there but the Travis CI testing isn't active.
`make.defs.${toolchain}` will be there.

PETSc nstream 

---

Makefile

add targets

---

Cxx11/dgemm-vector.cc
Cxx11/dgemm.cc

Forgot to make changes to DGEMM for prk::abs etc.

C++ DGEMM cleanup

---

JAVA/nstream.java
JAVA/p2p.java
JAVA/stencil.java
JAVA/transpose.java
PYTHON/p2p-numba.py
PYTHON/p2p-numpy.py
PYTHON/p2p.py

added a few Java serial kernels and fixed a python variable declaration

---

GO/README.md
GO/nstream.go

If no, why not? Jeff is lazy.
`./GO/README.md`

Go nstream

---

LUA/README.md
LUA/nstream.lua

If no, why not? Jeff is lazy.
See `LUA/README.md`.

add Lua nstream

---

PYTHON/README.md
PYTHON/nstream-mpi.py
PYTHON/nstream-numpy-mpi.py

If no, why not?  Jeff is lazy.

mpi4py nstream

---

PYTHON/README.md
PYTHON/nstream-mpi.py
PYTHON/nstream-numpy-mpi.py
PYTHON/transpose-mpi.py
PYTHON/transpose-numpy-mpi.py
PYTHON/transpose-numpy.py

mpi4py nstream and transpose

---

PYTHON/nstream-numba.py
PYTHON/transpose-numba.py

nstream with numba goes ~2x faster (~2 GB/s vs ~5 GB/s).
transpose with numba goes ~10x slower (~140 MB/s vs ~1500 MB/s).
The latter might be user error, but I tried a few different things with no change.

add Numba for nstream and transpose

---

Cxx11/Makefile
Cxx11/nstream-dpcpp.cc
Cxx11/nstream-sycl-explicit-usm.cc
Cxx11/nstream-sycl-explicit.cc
Cxx11/nstream-sycl-usm.cc
Cxx11/nstream-sycl.cc
Cxx11/stencil-2d-sycl.cc
Cxx11/stencil-sycl-usm.cc
Cxx11/transpose-2d-sycl.cc
Cxx11/transpose-dpcpp.cc
Cxx11/transpose-sycl-usm.cc
Cxx11/transpose-sycl.cc

Numerous simplifications and performance improvements to nstream.

SYCL ndrange transpose

---

Cxx11/nstream-sycl-explicit-usm.cc
Cxx11/nstream-sycl-explicit.cc
Cxx11/nstream-sycl-usm.cc
Cxx11/nstream-sycl.cc
Cxx11/pic-sycl.cc

SYCL nstream fix

---

PYTHON/stencil-numpy-mpi.py
PYTHON/stencil-numpy.py
PYTHON/transpose-numpy-mpi.py

The performance of this code is not good but we can debug that later.

mpi4py stencil

---

.gitignore
RUST/Makefile
RUST/nstream-iter/Cargo.toml
RUST/nstream-iter/src/main.rs
RUST/nstream-unsafe/Cargo.toml
RUST/nstream-unsafe/src/main.rs

- [ X ] nstream
- [ X ] Yes
If no, why not?
(not tested)
There are many good reasons why Travis CI support may not be part of your PR.
You or someone else can always add it later.
In many cases, we will add it later

Rust nstream variants

---

C1z/transpose-2d-openmp.c
GO/Makefile
GO/dgemm.go
GO/transpose.go

I've seen enough to conclude that Go has all of the downsides of Rust for numerical computing, and none of the good sides of anything.  The matrix transpose operator `T()` is useless and I see no way to do C+=A*B with matrices using the Matrix features.

Go transpose and dgemm

---

RUBY/nstream.rb

If this pull request is providing a new implementation of the PRKs,
please use the following template.
Note that checking all of the boxes is not required.

add ruby nstream

---

RUST/Makefile
RUST/dgemm/Cargo.toml
RUST/dgemm/src/main.rs
RUST/legacy/p2p.rs
RUST/legacy/stencil-old.rs
RUST/legacy/stencil.rs
RUST/legacy/transpose.rs
RUST/nstream-iter/src/main.rs
RUST/nstream-unsafe/src/main.rs
RUST/nstream/src/main.rs
RUST/p2p/src/main.rs
RUST/stencil/src/main.rs
RUST/transpose/src/main.rs

Inspired by @jedbrown's post on the BLIS mailing list...

Rust dgemm

---

Cxx11/nstream-tbb.cc
Cxx11/p2p-hyperplane-tbb.cc
Cxx11/p2p-innerloop-tbb.cc
Cxx11/p2p-tasks-tbb.cc
Cxx11/p2p-tbb.cc
Cxx11/prk_tbb.h
Cxx11/prk_util.h
Cxx11/stencil-tbb.cc
Cxx11/transpose-tbb.cc

Remove use of deprecated/removed APIs and use `global_control` etc.

TBB updates

---

SCALA/Makefile
SCALA/README.md
SCALA/nstream.scala

Small fix to make it compilable. The script mode still works.

---

C1z/nstream-target.c
FORTRAN/nstream-openmp-target.F90
common/make.defs.hip

The nstream validation change should be made everywhere but this is a start.

HIP and nstream validation

---

Cxx11/dgemm-cublas.cu
Cxx11/dgemm-mpi-cublas.cu
Cxx11/dgemm-multigpu-cublas.cu
Cxx11/nstream-cublas.cu
Cxx11/nstream-cuda.cu
Cxx11/nstream-managed-cuda.cu
Cxx11/prk_cuda.h
Cxx11/prk_mpi.h
Cxx11/transpose-cublas.cu
Cxx11/transpose-cuda.cu

better CUDA allocation

---

Cxx11/transpose-cuda.cu

I did a bad job of integrating the Mark Harris blog algorithm the first time...

Fix CUDA transpose

---

.gitignore
Cxx11/Makefile
FORTRAN/Makefile
FORTRAN/nstream-cufortran.cuf
FORTRAN/transpose-openmp-target.F90
FORTRAN/transpose-stdpar.F90

CUDA Fortran

---

Cxx11/nstream-onemkl.cc
common/make.defs.oneapi

oneAPI updates

---

FORTRAN/stencil-taskloop-openmp.F90

thanks to @mbycklin for this contribution.

fix error in OpenMP computation of norm

---

Cxx11/opencl.hpp
Cxx11/prk_opencl.h

this ancient one does not compile with ICPX or Clang when C++20 is enabled

update OpenCL C++ header

---

.gitignore
Cxx11/nstream-kokkos.cc
RUST/Makefile
RUST/dgemm-blis/Cargo.toml
RUST/dgemm-blis/src/main.rs
RUST/dgemm-iter/Cargo.toml
RUST/dgemm-iter/src/main.rs
RUST/dgemm-rayon/Cargo.toml
RUST/dgemm-rayon/src/main.rs
RUST/dgemm/Cargo.toml
RUST/nstream-iter/Cargo.toml
RUST/nstream-rayon/Cargo.toml
RUST/nstream-rayon/src/main.rs
RUST/transpose-iter/Cargo.toml
RUST/transpose-iter/src/main.rs
RUST/transpose-rayon/Cargo.toml
RUST/transpose-rayon/src/main.rs
RUST/transpose/src/main.rs

Added relevant dependencies to `Cargo.toml` files, which will prompt `cargo` to fetch and build relevant dependencies.
Fixed a minor issue with `nstream-kokkos.cc` to account for changes introduced as part of the `3.7.00` release.
All results obtained with using 10 iterations over 64million elements.
| Language/Kernels  | Rate (MB/s) | Comments |
| ------------- | :-------------: | :-------------: |
|RUST/nstream-iter | 77813.238  | serial |
|RUST/nstream-unsafe | 78711.622  | serial |
|RUST/nstream | 78955.383  | serial |
| C1z/nstream  |  80771.444   | serial |
| C1z/nstream-mpi  |  136195.568   | 16 MPI ranks |
| C1z/nstream-petsc  |  159297.680   | 16 MPI ranks |
| RUST/nstream-rayon | 162295.541 | thread-parallel |
| C1z/nstream-openmp  | 163650.220 | thread-parallel | 
All results …

Add multi-threaded rust kernels for nstream/transpose/dgemm 

---

Cxx11/dgemm-onemkl.cc
Cxx11/dgemm-sycl.cc
Cxx11/generate-sycl-stencil.py
Cxx11/nstream-dpcpp.cc
Cxx11/nstream-onedpl.cc
Cxx11/nstream-onemkl.cc
Cxx11/nstream-sycl-explicit-usm.cc
Cxx11/nstream-sycl-explicit.cc
Cxx11/nstream-sycl-usm.cc
Cxx11/nstream-sycl.cc
Cxx11/p2p-hyperplane-sycl.cc
Cxx11/pic-sycl.cc
Cxx11/prk_sycl.h
Cxx11/stencil-2d-sycl.cc
Cxx11/stencil-sycl-usm.cc
Cxx11/stencil-sycl.cc
Cxx11/stencil_sycl.hpp
Cxx11/transpose-2d-sycl.cc
Cxx11/transpose-dpcpp.cc
Cxx11/transpose-sycl-usm.cc
Cxx11/transpose-sycl.cc
Cxx11/xgemm-onemkl.cc
common/make.defs.oneapi

Update Intel SYCL compiler driver. Update device selectors and accessors to SYCL2020.

SYCL2020ification

---

MPIOPENMP/Synch_p2p/p2p.c
OPENMP/Synch_p2p/p2p.c

this is working on Orin, which is ARM A78ae w/ 12 cores for SYNCHRONOUS = 0 and 1
closes https://github.com/ParRes/Kernels/issues/611

replace omp flush with proper used of seq_cst atomics

---

.gitignore
CHAPEL/COPYRIGHT
CHAPEL/LICENSE
CHAPEL/Makefile
CHAPEL/README.md
CHAPEL/dgemm-summa.chpl
CHAPEL/dgemm.chpl
CHAPEL/nstream.chpl
CHAPEL/p2p-serial-fast.chpl
CHAPEL/pic.chpl
CHAPEL/random_draw.c
CHAPEL/random_draw.h
CHAPEL/sparse.chpl
CHAPEL/stencil-opt.chpl
CHAPEL/stencil-serial.chpl
CHAPEL/stencil.chpl
CHAPEL/transpose-serial.chpl
CHAPEL/transpose.chpl

Code take directly from https://github.com/chapel-lang/chapel/tree/08f3e9c8414d0aeedaa9ad8667edc556c0cb86e8/test/studies/prk
Authorship, according to the source file comments:
dgemm-summa.chpl:       Contributed by Rahul Ghangas (ANU)
dgemm.chpl:             Contributed by Engin Kayraklioglu (GWU)
nstream.chpl:           Contributed by Engin Kayraklioglu (GWU)
pic.chpl:               Contributed by Engin Kayraklioglu (GWU)
sparse.chpl:            Contributed by Engin Kayraklioglu (GWU)
stencil-serial.chpl:    Contributed by Ben Albrecht, Ben Harshbarger (Cray Inc.)
stencil.chpl:           Contributed by Ben Albrecht, Ben Harshbarger (Cray Inc.),
p2p-serial-fast.chpl:   Contributed by Ben Albrecht (Cray Inc.)
transpose-serial.chpl:  Contributed by Ben Albrecht (Cray Inc.)
transpose.chpl: …

add Chapel from upstream

---

Cxx11/transpose-cuda.cu
Cxx11/transpose-kernel.h

This works as well as the tuned version if the parameters are right...

transpose cuda block strided
