SHMEM/Synch_p2p/p2p.c, SHMEM/Transpose/transpose.c
pSync and pWrk arrays were not sized correctly, leading to memory
corruption.  pSync arrays also do not need to be re-initialized after
they are used.  _SHMEM_* constants are deprecated; replaced with new
SHMEM_ constants, if SHMEM_ was already used in the same file.
Signed-off-by: James Dinan <james.dinan@intel.com>
=> Fix errors in SHMEM collecives in transpose and p2p

MPIRMA/Stencil/stencil.c, MPIRMA/Synch_p2p/p2p.c, MPIRMA/Transpose/transpose.c, include/par-res-kern_mpi.h
When we only have MPI-2, we need to work around the lack of MPI lock_all, flush, and win_allocate.
=> New MPI-2 workarounds

.travis.yml, travis/install-mpi.sh
This does not address the Hydra-only download required for Sandia OpenSHMEM, just the MPICH 3.2 failures.
=> Travis ci mpichorg failover

SHMEM/Stencil/stencil.c, common/SHMEM_bail_out.c
I have updated the SHMEM_bail_out.c file to eliminate an allocation error in the pSync array.  I have also updated the SHMEM Stencil implementation to eliminate the error that arises when one of the input dimensions is not divisible by the number of tiles along that axis.
=> SHMEM Bug Fixes

SHMEM/Stencil/Makefile
Stencil has a dependence on libm, so it should be included in LIBS in
the stencil makefile.  This was removed in error in ac5bf13ea.
Signed-off-by: James Dinan <james.dinan@intel.com>
=> Add -lm back to Stencil LIBS

FORTRAN/Stencil/stencil-pretty.f90
@rfvander Can you explain to me why changing the initialization of A does not impact the correctness of stencil?
=> make Fortran init of A agree with C - somehow doesn't affect correctness

SHMEM/Stencil/stencil.c, SHMEM/Transpose/transpose.c
shmem_broadcast* behaves like shmem_put and thus requires SHMEM
synchronization operations to complete remotely.  for our purposes
shmem_barrier_all is good for this.
=> SHMEM collectives are one-sided

SHMEM/Synch_p2p/p2p.c, include/par-res-kern_general.h
```
cd SHMEM/Synch_p2p;         make p2p       "DEFAULT_OPT_FLAGS   = -O3"
make[1]: Entering directory `/home/travis/travis/src/PRK/SHMEM/Synch_p2p'
oshcc -O3 -DSHMEM     -I../../include -c p2p.c
p2p.c: In function ‘main’:
p2p.c:139:7: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat]
p2p.c:139:7: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat]
p2p.c:158:7: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat]
p2p.c:158:7: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat]
p2p.c: In function ‘prk_malloc’:
../../include/par-res-kern_general.h:135:19: warning: ignoring return value of …
```
=> Cleanup warnings in synch_p2p code

SHMEM/Transpose/Makefile, SHMEM/Transpose/transpose.c
Fix a race in the iterations loop where iterations can overlap resulting in data corruption and deadlock.  The fix adds another set of flags to inform the sender that the receiver is ready to receive the message.
Note: this fix will have a negative impact on performance of the flag update is blocking in the SHMEM library.
=> Add RTR flags to fix sync race in PRK Transpose

include/par-res-kern_general.h
_mm_malloc depended on UPC, but _mm_free did not.
this could lead to failures in free.
=> match preprocessor logic for _mm_{malloc,free}

Makefile, common/make.defs.pgi
- PGI fine for serial (C)
- PGI fine for OpenMP (C)
- PGI not fine for Fortran except OpenMP (see https://github.com/ParRes/Kernels/issues/140 for details)
=> add make.defs example for PGI compilers

.travis.yml, travis/install-fgmpi.sh
I am debugging these failures but since they are mostly (probably) not the fault of the PRK code itself, mark them as XFAIL.
=> add some AMPI, Charm++, FGMPI, etc to XFAIL

.travis.yml
These are passing now.  FG-MPI passes some of the time, but not reliably, so it stays on the XFAIL list.
=> remove CAF and BUPC from XFAIL

FORTRAN/Stencil/stencil-coarray.f90, FORTRAN/Synch_p2p/p2p-coarray.f90, FORTRAN/Transpose/transpose-coarray.f90
yes, this has the negative effect of allowing builds to succeed when
programs will fail at runtime, but i prefer that in the PRK project.
=> disable coarrays when PGI is used

Cxx11/Makefile, Cxx11/prk_util.h, Cxx11/transpose-vector-pstl.cc, common/make.defs.gcc, common/make.defs.intel
Merging now is useful because this involves build system changes, which tend to diverge more quickly than the source.
No Travis testing yet because it is not clear than any of the compilers Travis supports will provide PSTL (still need to debug GCC).
=> initial Parallel STL port (transpose)

.travis.yml, FORTRAN/Makefile, common/FORTRAN.defs, travis/build-run-prk.sh, travis/install-deps.sh, travis/install-gcc.sh
this should save a little bit of time, at the expense of having to
inspect the logs to know what model failed (which we do for C++ and C1z)
=> consolidate Fortran testing in Travis

.travis.yml, travis/build-run-prk.sh, travis/install-deps.sh
this will save a lot of time because we have to build MPICH from source
on Linux, which we can now do once instead of four times.
=> consolidate MPI testing

Cxx11/generate-cxx-stencil.py, Cxx11/stencil-vector-tbb.cc, Cxx11/stencil_tbb.hpp, Cxx11/transpose-vector-tbb.cc
transpose implements both 1D and 2D blocking - we compile the latter because it is
faster and consistent with the other blocked implementations.
stencil only implements 2D blocking and is currently the only stencil
implementation with explicit blocking.
=> use lambdas instead of functors in TBB transpose and stencil

Cxx11/prk_util.h, common/make.defs.gcc, common/make.defs.llvm
- add -ffast-math to both GCC and Clang options.
- use a better Clang SIMD pragma (thanks, Hal).
- document useful Clang options in example make.defs.
=> GCC and Clang fast-math plus Clang SIMD

Cxx11/generate-cxx-stencil.py, Cxx11/stencil_cilk.hpp, Cxx11/stencil_kokkos.hpp, Cxx11/stencil_openmp.hpp, Cxx11/stencil_pgnu.hpp, Cxx11/stencil_pstl.hpp, Cxx11/stencil_raja.hpp, Cxx11/stencil_rangefor.hpp, Cxx11/stencil_seq.hpp, Cxx11/stencil_stl.hpp, Cxx11/stencil_target.hpp, Cxx11/stencil_taskloop.hpp, Cxx11/stencil_tbb.hpp
- code generator only needs to define RESTRICT for OpenMP target,
as the rest use stl::vector
- GPU-style target means the functions are invoked on host, so must
remove "declare target" for correctness (caught by LLVM 5)
=> cleanup OpenMP target stencil

travis/build-run-prk.sh
`cafrun` is not parsing arguments in any sane way currently. This is a work around (hopefully) to get it working again. TL;DR; `--oversubscribe` should come after `-np <N>`
Hoping this fixes the failing build/test on Travis.
=> Fix cafrun fix (replaces/fixes/hacks PR #285)

Cxx11/prk_util.h, Cxx11/transpose-kokkos.cc
i cannot solve this simple issue:
```
transpose-kokkos.cc:54:17: error: 'OpenMP' in namespace 'Kokkos' does not name a type
typedef Kokkos::OpenMP Space;
```
looking at the examples was not helpful.  if the Kokkos people want me
to stop thinking RAJA is much easier to use and just as fast, they
should submit pull requests.
=> Kokkos is hard to use so give up trying to use explicit Space

.travis.yml, AMPI/AMR/amr.c, MPI1/AMR/amr.c, travis/build-run-prk.sh, travis/install-deps.sh, travis/install-libfabric.sh, travis/install-mpi.sh
- libfabric 1.3.0 has issues on Mac per https://travis-ci.org/ParRes/Kernels/jobs/309794625
- Open-MPI `--oversubscribe` required on Mac now that we use it for MPI-1 not just OpenCoarrays
- Python 3 env in Travis sucks (does not find `process_time`) so we XFAIL.
- Fix AMR bug (MPI communicator was `int` not `MPI_Comm`, which only Open-MPI notices).
=> Travis CI cleanup

Cxx11/Makefile, Cxx11/nstream-cublas.cu, Cxx11/nstream-cuda.cu, Cxx11/prk_cuda.h, Cxx11/transpose-cublas.cu, Cxx11/transpose-cuda.cu
Tested `float` with Coriander.  Tested `double` on V100 and CUDA 9.0
=> CUDA: support both float and double

CHARM++/Stencil/Makefile
Fixes minor spacing issue in the Charm++ Stencil Makefile's flags.
=> Fix spacing in Charm++ Stencil Makefile

Cxx11/nstream-kokkos.cc
This address issue #377 
There are fences missing hence you wont' measure what you think on
asynchronous backends such as CUDA or HPX.  This also fixes using the actual name of the exec space instead of typeid.
Example for CUDA on V100:
Original:
Parallel Research Kernels version 2.16
C++11/Kokkos STREAM triad: A = B + scalar * C
Number of iterations = 1
Vector length        = 100000000
Offset               = 0
Kokkos execution space: N6Kokkos4CudaE
Solution validates
Rate (MB/s): 422188 Avg time (s): 0.00757957
With fences (and name fix):
Parallel Research Kernels version 2.16
C++11/Kokkos STREAM triad: A = B + scalar * C
Number of iterations = 1
Vector length        = 100000000
Offset               = 0
Kokkos execution space: Cuda
Solution validates
Rate (MB/s): 842600 Avg time (s): …
=> Cxx11 nstream-kokkos

LEGION/Stencil/stencil.cc
This change keeps the Legion stencil code up-to-date with the current Legion default mapper interface.
=> Legion update to match a minor default mapper interface update

Cxx11/nstream-explicit-sycl.cc, Cxx11/nstream-sycl.cc, Cxx11/prk_util.h, Cxx11/stencil-sycl.cc, Cxx11/transpose-explicit-sycl.cc, Cxx11/transpose-sycl.cc
This allows the SYCL benchmarks in PRK to be compiled with hipSYCL. Included changes:
* Like triSYCL, hipSYCL does not advertise support for Khronos fp64 or spir extensions, since it does not use OpenCL. So, on hipSYCL, tests should be carried out even if these extensions are not present.
* Like triSYCL, hipSYCL does not need prebuilding kernels
* Depending on the hipSYCL compilation target, CPU and GPU backends may not be available, which may then cause the benchmark to abort since the device selector throws an exception (because no matching device could be found). This is fixed by introducing the `SYCL_TRY_CPU_QUEUE` and `SYCL_TRY_GPU_QUEUE` macros.
The cpu/gpu portions of the benchmarks are only enabled if these macros are set. If not on hipSYCL both are enabled; on hipSYCL they are …
=> Add initial hipSYCL support

C1z/generate-c-stencil.py, C1z/stencil_target.h
Same as previous by @jeffhammond in `Cxx11/`:
> - GPU-style target means the functions are invoked on host, so must
>   remove "declare target" for correctness (caught by LLVM 5)
I encountered the C version of ParRes/Kernels#277 .  I did not create a new issue because the fix was simple and obvious.
=> clean OpenMP target stencil in C1z

common/make.defs.ibmp9nv
1500-029: (W) WARNING: subprogram cl::Platform::getDevices(cl_device_type, std::vector<Device> *) could not be inlined into cl::Context::Context(cl_device_type, cl_context_properties *, void (*)(const char *, const void *, ::size_t, void *), void *, cl_int *).
[ci skip]
=> xlc suppress warning in OpenCL code

.gitignore, Cxx11/Makefile, Cxx11/nstream-celerity.cc, common/make.defs.gcc, common/make.defs.llvm
Need to add hipSYCL support first, which might be hard.
See https://github.com/ParRes/Kernels/blob/master/doc/SYCL.md#celerity.  The `make.defs` examples are there for GCC and LLVM, but since hipSYCL is based on Clang, the changes are identical.
=> add Celerity nstream

FG_MPI/Transpose/Makefile, MPI1/Transpose/Makefile, MPIOPENMP/Transpose/Makefile, MPIRMA/Transpose/Makefile, MPISHM/Transpose/Makefile
PGI doesn't accept `-std=c99` so remove from build system.  Compilers needing a flag to support C99, which are now limited to the old ones, must set it in `make.defs`.
=> remove C99 flag (PGI fix)

Cxx11/nstream-sycl-usm.cc
Fixing a bug where A is freed but then referenced again discovered by Peter Zuzek from Codeplay.
=> The variable A is freed and used again, free once use is complete

C1z/Makefile, C1z/nstream-petsc.c, C1z/prk_petsc.h, C1z/transpose-petsc.c, common/make.defs.cray, common/make.defs.gcc, common/make.defs.intel, common/make.defs.llvm, common/make.defs.oneapi
This is slow with MPI because of PETSc and doesn't check for correctness.
=> Petsc transpose

Cxx11/Makefile, Cxx11/nstream-sycl-explicit-usm.cc, Cxx11/nstream-sycl-explicit.cc, Cxx11/nstream-sycl-usm.cc, Cxx11/nstream-sycl.cc, Cxx11/prk_sycl.h, Cxx11/stencil-sycl-usm.cc, Cxx11/stencil-sycl.cc, Cxx11/transpose-sycl-explicit.cc, Cxx11/transpose-sycl-usm.cc, Cxx11/transpose-sycl.cc, common/make.defs.llvm
previously, we tried to detect device presence with preprocessor macros
and querying for the SPIR extension (because that worked for
ComputeCpp).  because Intel Level Zero does not support that method, we
cannot use it in DPC++ without adding even more clunkiness.
this removes SPIR/PTX queries and uses try-catch for every device in all
SYCL implementations.  if we find implementations that do not throw
properly when devices do not work, then that is on them (we will file
bug reports) but we can work around that other ways that are yet to be
determined.
=> remove clunky device detection code

Cxx11/nstream-sycl-explicit-usm.cc
Signed-off-by: James Brodman <james.brodman@intel.com>
If this pull request is providing a new implementation of the PRKs,
please use the following template.
Note that checking all of the boxes is not required.
In some cases, only one box may be checked, *and that is totally fine.*
- [X ] nstream
If no, why not?
There are many good reasons why Travis CI support may not be part of your PR.
You or someone else can always add it later.
In many cases, we will add it later
for a new user …
=> [SYCL][USM] Fix byte size calculation

Cxx11/Makefile, Cxx11/nstream-cuda.cu, Cxx11/nstream-dpcpp.cc
This fixes performance differences between CUDA and DPC++ due to a default block size of 32.
=> nstream blocksize for GPU

Csharp/nstream.cs, Csharp/transpose.cs
MCS 4.6 on Ubuntu 18 AAarch64 didn't like the previous implementation and I am fine with trading potential robustness for portability.
=> make input parsing work with older C# compilers

C1z/nstream-alloc-target.c, C1z/nstream-memcpy-target.c, C1z/nstream-usm-target.c
Signed-off-by: Vyacheslav Zakharin <vyacheslav.p.zakharin@intel.com>
If this pull request is providing a new implementation of the PRKs,
please use the following template.
Note that checking all of the boxes is not required.
- [X ] Yes
=> Fixed device numbers for memory APIs.

PYTHON/nstream-numba.py
If this pull request is providing a new implementation of the PRKs,
please use the following template.
Note that checking all of the boxes is not required.
Before:
```
python PYTHON/nstream-numba.py 100 100000
Python version =  3.7
Numpy version  =  1.16.4
Parallel Research Kernels version 
Python Numpy STREAM triad: A = B + scalar * C
Number of …
```
=> nstream-numba: get good performance by pulling 0th iteration call out of loop

Cxx11/p2p-tbb.cc, Cxx11/prk_tbb.h
Opting out or removing more deprecated interfaces (atomic, parallel_do), maintaining backwards compatibility. Makes the code a little bit ugly. :-)
Explicit include of `tbb/version.h` has to be removed to maintain backwards compatibility. Issue created by previous PR.
=> Enable P2P for oneTBB

FORTRAN/nstream-openmp-target.F90, common/make.defs.cray, common/make.defs.cuda, common/make.defs.gcc, common/make.defs.hip, common/make.defs.intel, common/make.defs.llvm, common/make.defs.nvhpc, common/make.defs.oneapi, common/make.defs.pgi
AMD Flang really needs `schedule(static,1)`.  Thanks @mjklemm.
=> add GPU_SCHEDULE to Fortran nstream-openmp-target

JULIA/stencil.jl
I just saw this thread on [twitter](https://twitter.com/science_dot/status/1375115999997927426), so I might as well chip in a bit.
Changes:
1. `do_add` -> `do_add!` : When a function mutates its arguments (`A` in this case), it is Julia convention to add a `!` at the end of the function name to alert the user.
2. Switching the loop order - Julia is column major, and this incurs a heavy performance hit.
3. `1:n` -> `Base.OneTo(n)` This method uses a type to tell the compiler that the loops start at `1`, which is very useful for loop unrolling and SIMD shenanigans. Usually not worth it if it's not a super tight loop.
4. `@inbounds` elides bounds checking.
5. `1.0` to `one(eltype(A))`: This calls a function which determines what is the `identity` element for the collection of A. This is …
=> Small Julia fixes

Cxx11/Makefile, Cxx11/nstream-kokkos.cc, Cxx11/prk_kokkos.h, Cxx11/stencil-kokkos.cc, Cxx11/transpose-kokkos.cc, common/make.defs.nvhpc
Apparently, `auto x={n,n}` can't be used in `MDRangePolicy` :-(
=> Kokkos CUDA fixes

FORTRAN/stencil-openacc.F90, FORTRAN/transpose-openacc.F90
non-constant tiling was supported by NVHPC not GCC,
and was not standard anyways.
=> replace non-constant tiling with automatic tiling

Cxx11/Makefile, Cxx11/xgemm-cublas.cc, Cxx11/xgemm-cublas.cu
=> xgemm cublas

Cxx11/prk_kokkos.h, Cxx11/stencil-kokkos.cc, Cxx11/transpose-kokkos.cc
Kokkos kernels don't compile under the latest release. Math functions such as fabs have been moved from the Kokkos::Experimental namespace to the Kokkos namespace. Additionally, directly including headers aside from Kokkos_Core.hpp is disallowed.
https://github.com/ParRes/Kernels/issues/640
=> Fix Kokkos kernels for Kokkos 4.3.0

Cxx11/Makefile, Cxx11/dgemm-cublas-cudastf.cu, Cxx11/dgemm-cudastf.cu, Cxx11/p2p-cudastf.cu, Cxx11/stencil-cudastf.cu, Cxx11/transpose-cudastf.cu, ci/install-cudastf.sh, common/make.defs.cuda
CUDASTF implementation
- [ x] stencil
use ci/install-cudastf.sh
use make.defs.cuda
cd Cxx11/ << We need to define Cxx17 ?
make stencil-cudastf 
- [ x] Yes
=> [WIP] CUDASTF implementation of the stencil example

JULIA/README.md
This PR fixes the `-e` typo pointed out by @jeffhammond in https://github.com/ParRes/Kernels/issues/646#issuecomment-2477403014_
With the typo fixed, I can **not** confirm/reproduce that the command (`using MPI; MPI.install_mpiexecjl()`) only works in the REPL and not via `-e`:
```
cb@mm ~/repos/Kernels/JULIA git:(main)
➜ JULIA_DEPOT_PATH=$(pwd)/.julia julia --project -e 'using MPI; MPI.install_mpiexecjl()'
[ Info: Installing `mpiexecjl` to `/Users/carstenbauer/repos/Kernels/JULIA/.julia/bin`...
[ Info: Done!
```
=> Fix typo in Julia README.md

Cxx11/p2p-hyperplane-sycl.cc
For this example dependencies should already be represented by buffers/accessors as data dependencies.
`queue.wait()` seems unnecessary, and hurts performance by introducing extra host synchronization.
=> [SYCL] Remove unnecessary waits from P2P hyperplane

Cxx11/p2p-hyperplane-sycl-graph.cc
This modified example is using SYCL Graph which is a oneAPI vendor extension written against SYCL 2020.
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
Currently, this feature is only implemented in the Intel oneAPI C++/DPC++ compiler since 2024.0 release.  
Open source version available at: https://github.com/intel/llvm
Existing SYCL build configuration can be reused.
=> [SYCL ]Adding SYCL Graph version of p2p-hyperplane
